---
date: "2018-12-27T20:46:49-06:00"

title: About us
---

Whether its making a simple map or running complex analyses on satellite data,  students and researchers are often called upon to do some sort of geospatial analysis. `r emo::ji("world_map")`  

Fortunately, there are a wealth of tools available to do this, think R, Python and QGIS.`r emo::ji("hammer")`    

Unfortunately, a steep learning curve is often required to apply these tools, particularly when we don't all have a strong background in coding, GIS or remote sensing.  

The UQ Geospatial Analysis Community of Practice (sometimes UQGAC) tries to make this process a bit less painful, by sharing  our experiences, skills and tricks in a friendly and inclusive environment.    

`r emo::ji("woman_technologist")` We run monthly skill sharing tutorial sessions where a member of the community teaches us something they have learned along the way. 

This is usually on the last thursday of each month.  
See [upcoming events](/upcoming-events/) for the next session. 

And check out our [blog](/post/) for previous tutorials.  


If you want to get involved, just email Mitch at mitchel.rudge@uq.edu.au




