---
date: "2018-12-27T20:46:49-06:00"

title: Upcoming events
---

# "Things I wish I had known about R spatial" & Problem solving session IV

To end the year with a bang, we're doing a double session this month.

We will start with a short session on Spatial Analysis in R - **Things I wish I had known about R spatial** by Christina Buelow.

For the second half we will have another **problem solving session**.
As with previous problem-solving sessions, we will have a free-range discussion with the goal of helping people get back on track with their geospatial data analysis.
If you have a thorny problem, feel free to send it through to Nicholas Wiggins ([n.wiggins\@uq.edu.au](mailto:n.wiggins@uq.edu.au){.email}) ahead of the session and we will try to come up with a solution.

<br> <br>

**When** Thursday 24th November, 2:30 - 4:30pm

**Where** Online, a teams link will be sent out via email

<br> <br>

# Forward schedule

Here we have placeholders for upcoming workshops.
If you have something you would like to share with the community, please get in touch.

**December 9th**

End of year catch up at the River Quay Green at South Bank from 4pm.

-   Byo food and drinks for a picnic.
-   Bring family and friends.
-   Help decide on a new name for our Geospatial community.
