---
date: "2018-12-27T20:46:49-06:00"

title: Upcoming events
---



# Problem solving session

<br>

Something different for May: a problem solving session! 

Send through your geospatial questions (preferably about R, Python or QGIS), and we will try to come up with solutions.  
Then we will go through the solutions during the workshop, and put the examples up on the website for future reference.  




**When** Thursday 26th May 2022, 2:30 - 4:30pm


**Hybrid - Online + in person**
Location TBD, but somewhere at UQ St Lucia

check email for teams link. 
If you are not on the mailing list, email mitchel.rudge@uq.edu.au and request to be added. 

<br>
<br>

# Forward schedule 

Here we have placeholders for upcoming workshops. If you have something you would like to share with the community, 
please get in touch. 

**June 30**
TBC

**July 28**
TBC

**August 25**
Climate analysis in R - Ralph Trancoso da Silva 

**September 29**
TBC

**October 27**
Spatial analysis in R - Caitie Kuempel

**November 24**
TBC

**December 8**
End of year catch up


























